package ru.otus.otuskotlin.marketplace.common.backend.models

enum class MpStubCase {
    NONE,

    DEMAND_LIST_SUCCESS,
    DEMAND_CREATE_SUCCESS,
    DEMAND_READ_SUCCESS,
    DEMAND_UPDATE_SUCCESS,
    DEMAND_DELETE_SUCCESS,
    DEMAND_OFFERS_SUCCESS,

    PROPOSAL_LIST_SUCCESS,
    PROPOSAL_CREATE_SUCCESS,
    PROPOSAL_READ_SUCCESS,
    PROPOSAL_UPDATE_SUCCESS,
    PROPOSAL_DELETE_SUCCESS,
    PROPOSAL_OFFERS_SUCCESS,
}
