#!/bin/bash

VERS=7.10.1

for i in elasticsearch kibana logstash
do
    docker build -t $i:$VERS $i
done
docker pull wurstmeister/zookeeper:3.4.6
docker pull wurstmeister/kafka:2.12-2.5.0
docker pull obsidiandynamics/kafdrop:latest
