openapi: 3.0.3
info:
  title: Marketplace
  description: 'Учебный проект по созданию маркетплейса. Сервиса, на котором можно выставлять предложения и потребности
  , а также находить их возможные комбинации'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: proposal
    description: Рабоа с Потребностями
  - name: proposal
    description: Работа с Предложениями
paths:
  /proposal/list:
    post:
      tags:
        - proposal
      summary: Получить список Потребностей
      operationId: proposalList
      requestBody:
        description: Запрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpRequestProposalList'
        required: true
      responses:
        200:
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpResponseProposalList'

  /proposal/create:
    post:
      tags:
        - proposal
      summary: Создание Предожения
      operationId: proposalCreate
      requestBody:
        description: Запрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpRequestProposalCreate'
        required: true
      responses:
        200:
          description: Положительный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpResponseProposalCreate'

  /proposal/read:
    post:
      tags:
        - proposal
      summary: Получение информации о Предожения
      operationId: proposalRead
      requestBody:
        description: Запрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpRequestProposalRead'
        required: true
      responses:
        200:
          description: Положительный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpResponseProposalRead'

  /proposal/update:
    post:
      tags:
        - proposal
      summary: Обновление Предожения
      operationId: proposalUpdate
      requestBody:
        description: Запрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpRequestProposalUpdate'
        required: true
      responses:
        200:
          description: Положительный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpResponseProposalUpdate'

  /proposal/delete:
    post:
      tags:
        - proposal
      summary: Удаление Предожения
      operationId: proposalDelete
      requestBody:
        description: Запрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpRequestProposalDelete'
        required: true
      responses:
        200:
          description: Положительный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpResponseProposalDelete'

components:
  schemas:

    MpRequestProposalList:
      title: Запрос списка Потребностей
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpRequestBase'
        - $ref: '#/components/schemas/MpProposalListFilter'
          
          
    MpResponseProposalList:
      title: Ответ на запрос списка Потребностей
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpResponseBase'
        - type: object
          properties:
            proposals:
              type: array
              items:
                $ref: '#/components/schemas/MpProposal'

    MpProposalListFilter:
      title: Фильтр для поиска Потребностей
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpItemFilter'

    MpProposal:
      title: Предожение
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpItem'

    MpRequestProposalCreate:
      title: Запрос создания Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpRequestBase'
        - $ref: '#/components/schemas/MpProposalCreate'

    MpResponseProposalCreate:
      title: Ответ на запрос создания Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpResponseBase'
        - type: object
          properties:
            proposal:
              $ref: '#/components/schemas/MpProposal'

    MpProposalCreate:
      title: Запрос создания Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpItemCreate'


    MpRequestProposalRead:
      type: object
      properties:
        id:
          type: string

    MpResponseProposalRead:
      title: Ответ на запрос информации о Предожении
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpResponseBase'
        - type: object
          properties:
            proposal:
              $ref: '#/components/schemas/MpProposal'


    MpRequestProposalUpdate:
      title: Запрос изменения Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpRequestBase'
        - $ref: '#/components/schemas/MpProposalUpdate'

    MpResponseProposalUpdate:
      type: object

    MpProposalUpdate:
      title: Запрос обновления Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpItemUpdate'


    MpRequestProposalDelete:
      type: object
      properties:
        id:
          type: string

    MpResponseProposalDelete:
      title: Ответ на запрос удаления Предожения
      allOf:
        - $ref: './marketplace-base-api.yaml#/components/schemas/MpResponseBase'
        - type: object
          properties:
            proposal:
              $ref: '#/components/schemas/MpProposal'
            deleted:
              type: boolean
              title: Предожение удалено - true, false
