#POST http://marketplace.crowdproj.com/demand/list
POST http://{{url}}/demand/list
Content-Type: application/json

{}

###
POST http://localhost:8080/demand/create
Content-Type: application/json

{"createData": {"title": "Test Demand", "avatar": "icon://ok", "description": "Some Test Demand"}}

###
POST http://localhost:8080/demand/read
Content-Type: application/json

{"demandId": "d-7263"}

###
POST http://localhost:8080/demand/update
Content-Type: application/json

{"updateData": {"id": "d-rrt", "title": "Test Demand", "avatar": "icon://ok", "description": "Some Test Demand"}}

###
POST http://localhost:8080/demand/delete
Content-Type: application/json

{"demandId": "d-rrt"}

###
POST http://localhost:8080/demand/offers
Content-Type: application/json

{"demandId": "d-rrt"}

###
