POST http://{{url}}/proposal/list
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"}}

###
POST http://{{url}}/proposal/create
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"},"createData": {"title": "Test Proposal", "avatar": "icon://ok", "description": "Some Test Proposal"}}

###
POST http://{{url}}/proposal/read
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"},"proposalId": "p-7263"}

###
POST http://{{url}}/proposal/update
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"},"updateData": {"id": "p-rrt", "title": "Test Proposal", "avatar": "icon://ok", "description": "Some Test Proposal"}}

###
POST http://{{url}}/proposal/delete
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"},"proposalId": "p-rrt"}

###
POST http://{{url}}/proposal/offers
Content-Type: application/json

{"debug": {"stubCase": "SUCCESS"},"proposalId": "p-rrt"}

###
